Propagating the exit code of `puppet apply`
This change makes `omegaup-deploy-latest` terminate with a non-zero exit
code if there were failures while deploying.

diff --git a/templates/webhook/omegaup-deploy-latest.erb b/templates/webhook/omegaup-deploy-latest.erb
--- a/templates/webhook/omegaup-deploy-latest.erb
+++ b/templates/webhook/omegaup-deploy-latest.erb
@@ -1,3 +1,21 @@
 #!/bin/bash
 
-puppet apply /etc/puppet/modules/omegaup/manifests/<%= @manifest_name %>.pp
+puppet apply --detailed-exitcodes \
+  /etc/puppet/modules/omegaup/manifests/<%= @manifest_name %>.pp
+
+exitcode=$?
+# From https://puppet.com/docs/puppet/5.3/man/apply.html:
+case ${exitcode} in
+0|2)
+	# 0: The run succeeded with no changes or failures; the system was already in
+  #    the desired state.
+  # 2: The run succeeded, and some resources were changed.
+  exit 0
+  ;;
+*)
+  # 1: The run failed.
+	# 4: The run succeeded, and some resources failed.
+	# 6: The run succeeded, and included both changes and failures.
+  exit ${exitcode}
+  ;;
+esac
